version: '3.6'
services:
  db:
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./database:/var/lib/mysql"
      - "./sql:/docker-entrypoint-initdb.d"
  db_pma:
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  www:
    restart: always
    build: dockerfiles/www
    depends_on:
      - db
    volumes:
      - "./web:/var/www/html"
    environment:
      DB_ADDR: db
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - 8081:80
  daemon:
    restart: always
    build: dockerfiles/daemon
    depends_on:
      - db
    volumes:
      - "./scripts:/scripts"
    ports:
      - 27500:27500
    working_dir: /scripts
    command: perl ./hlstats.pl --db-host db --db-username root --db-password ${MYSQL_ROOT_PASSWORD} --db-name ${MYSQL_DATABASE} -dd
    networks:
      default:
        ipv4_address: 172.99.0.10
  awards:
    restart: always
    build: dockerfiles/daemon
    depends_on:
      - db
    volumes:
      - "./scripts:/scripts"
    working_dir: /scripts
    command: perl ./hlstats-awards.pl --db-host db --db-username root --db-password ${MYSQL_ROOT_PASSWORD} --db-name ${MYSQL_DATABASE}
  heatmaps:
    restart: always
    build: dockerfiles/www
    depends_on:
      - db
    volumes:
      - "./heatmaps:/data"
      - "./web:/var/www/html"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    working_dir: /data
    command: php generate.php --disable-cache

networks:
  default:
    name: hlds_network
    external: true
